eunimartproject/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('votes.urls')),
]

votes/urls.py

from django.urls import path
from . import views

app_name = 'votes'
urlpatterns = [
    path('registration/', views.registration, name='registration'),
    path('', views.login_in, name='login'),
    path('logout/', views.logout_out, name='logout'),
    path('regions/', views.all_regions, name='allregions'),
    path('regions/<int:region_id>/', views.details, name='details'),
    path('regions/<int:region_id>/votes/', views.vote, name='vote'),
]

votes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Region(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Voter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    region = models.ManyToManyField(Region, null=True, blank=True)
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Candidate(models.Model):
    question = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, unique=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

votes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout
from .models import *


def index(request):
    if request.method == 'POST':
        Region.objects.create(
            name=request.POST['name']
        )
        return HttpResponseRedirect(reverse('votes:allregions'))
    return render(request, 'votes/index.html')


def registration(request):
    if request.method == 'POST':
        user = User.objects.create_user(
            username=request.POST['username'],
            password=request.POST['password'],
            email=request.POST['email'],
        )
        Voter.objects.create(
            name=request.POST['name'],
            address=request.POST['address'],
            user=user
        )

        return HttpResponseRedirect(reverse('votes:login'))
    return render(request, 'votes/registration.html', {})


def login_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('votes:allregions'))
        else:
            return render(request, 'votes/login.html')
    return render(request, 'votes/login.html')


def logout_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('votes:login'))


@login_required(login_url='/login/')
def all_regions(request):
    region_list = Region.objects.all()
    admin = False
    if request.user.is_superuser:
        admin = True
    if request.method == 'POST':
        Region.objects.create(
            name=request.POST['name']
        )

    return render(request, 'votes/regions.html', {'form': region_list, 'admin': admin})


@login_required(login_url='/login/')
def details(request, region_id):
    region = get_object_or_404(Region, id=region_id)
    user = request.user
    admin = False
    if request.user.is_superuser:
        admin = True
    if request.method == 'POST':
        region.candidate_set.create(
            name=request.POST['name']
        )
    return render(request, 'votes/details.html', {"region": region, 'admin': admin, 'user': user})


@login_required(login_url='/login/')
def vote(request, region_id):

    region = get_object_or_404(Region, pk=region_id)
    user = request.user
    try:
        voter = Voter.objects.get(user=user)
    except:
        return HttpResponse('invalid user')
    # region.voter_set.add(voter)
    # voter.save()
    # print(voter.region)
    try:
        selected_candidate = region.candidate_set.get(pk=request.POST['candidate'])
    except (KeyError, Candidate.DoesNotExist):
        return render(request, 'votes/details.html', {
            'region': region,
            'error_message': "You didn't select a candidate.",
        })
    else:
        selected_candidate.votes += 1
        selected_candidate.save()
        return HttpResponseRedirect(reverse('votes:details', args=(region.id,)))

votes/templates/votes/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        {% load static %}
    <link href="{% static 'details.css' %}" rel="stylesheet">
</head>
<body>
{% if error_message %}
<h1>{{error_message}} </h1>
{% endif %}
{% if admin %}
<h1>Hello admin {{user.username}}</h1>
<h2>Add New Candidate</h2>

<form action="" method="post" >
    {% csrf_token %}
    name : <input type="text" name="name">
    <button type="submit">add new candidate</button><br>

</form>
{% endif %}
<h1>{{ region.name }}</h1>


<form action="{% url 'votes:vote' region.id %}" method="post">
{% csrf_token %}
{% for candidate in region.candidate_set.all %}
    <input type="radio" name="candidate" id="candidate{{ forloop.counter }}" value="{{ candidate.id }}">
    <label for="candidate{{ forloop.counter }}">{{ candidate.name }}</label>
    ---{{candidate.votes}}
    <br>
{% endfor %}<br>
<input type="submit" value="Vote">
</form><br><br>
    <div class="log">
        <button>
            <a href="{% url 'votes:logout' %}">logout</a>
        </button>
    </div>

</body>
</html>

votes/templates/votes/index.html
<form action="." method="post" >
    {% csrf_token %}
    <h2>add region here </h2>
    name : <input type="text" name="name"><br>

    <button type="submit">Login</button><br>

</form>

    <a href="{% url 'votes:logout' %}">logout</a>

votes/templates/votes/login.html
<head>
    {% load static %}
    <link href="{% static 'login.css' %}" rel="stylesheet">
</head>

<body>

  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <form class="form-signin" action="" method="post">
                {% csrf_token %}
              <div class="form-label-group">
                  <label for="username">username</label>
                <input type="text" id="username" class="form-control" placeholder="Username" required autofocus name="username">

              </div>

              <div class="form-label-group">
                  <label for="inputPassword">Password</label>
                <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">

              </div>

              <input class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">
                <br><br>
              <a href="{% url 'votes:registration'%}"> Registraion</a>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

votes/templates/votes/regions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'region.css' %}" rel="stylesheet">
</head>
<body>
{% if admin %}
<h1>Hello admin {{user.username}}</h1>
<h2>Add New Region</h2>
<div class="container">
    <form action="" method="post" >
        {% csrf_token %}
        <div>
            <label for="region-name">name </label>
         <input id="region-name" type="text" name="name">
        <button type="submit">add new region</button><br>
        </div>
    </form>
    {% endif %}
    </body>
    {% for region in form %}
    <div class="region-list">
        <br>
        <a href="/regions/{{region.id}}/">{{ region.name }}</a>
        {% endfor %}
    </div><br><br>
    <div class="log">
        <button>
            <a href="{% url 'votes:logout' %}">logout</a>
        </button>
    </div>
</div>
</html>

votes/templates/votes/registration.html
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        {% load static %}
    <link href="{% static 'registration.css' %}" rel="stylesheet">
</head>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">User Registration Form</h5>
                <form action="." method="post" >
                    {% csrf_token %}
                    User Name : <input type="text" name="username"><br>
                    Password : <input type="password" name="password"><br>
                    email : <input type="text" name="email"><br>
                    name : <input type="text" name="name"><br>
                    address : <input type="text" name="address"><br>
                    <input type="submit" value="Register"/><br>
                    <a href="{% url 'votes:login' %}">Login</a>

                </form>
            </div>
        </div>
      </div>
    </div>
  </div>

<a href = "{% url 'votes:login' %}">Login</a><br>

